kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2-retain
  selfLink: /apis/storage.k8s.io/v1/storageclasses/gp2-retain
  uid: c6146cc2-d037-11e9-9a2b-0a6a7345c60e
  resourceVersion: '587328'
  creationTimestamp: '2019-09-05T23:49:17Z'
provisioner: kubernetes.io/aws-ebs
parameters:
  fsType: xfs
  type: gp2
reclaimPolicy: Retain
volumeBindingMode: Immediate
