apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-lake
  labels:
    pipeline: training
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-retain
  awsElasticBlockStore:
    volumeID: vol-0f8cc0b50b40b5a77
    fsType: xfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-store
  labels:
    pipeline: inference
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-retain
  awsElasticBlockStore:
    volumeID: vol-0842a2aeb41db3dc7
    fsType: xfs
