apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-data-lake
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-data-lake
  template:
    metadata:
      labels:
        role: nfs-data-lake
    spec:
      nodeSelector:
        pipeline: training
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: pvc
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: data-lake
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-model-store
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-model-store
  template:
    metadata:
      labels:
        role: nfs-model-store
    spec:
      nodeSelector:
        pipeline: inference
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: pvc
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: model-store
