apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-lake
  labels:
    pipeline: nfs-training
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.30.227.157
    #nfs-data-lake.default.svc.cluster.local
    path: "/"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-model-store
  labels:
    pipeline: nfs-inference
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.30.249.5
    #nfs-model-store.default.svc.cluster.local
    path: "/"
