kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-data-lake
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      pipeline: nfs-training
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-model-store
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      pipeline: nfs-inference
